FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./src /app
COPY pyproject.toml /app/
COPY docker/run_monitor.sh /app/run_monitor.sh
RUN chmod +x /app/run_monitor.sh

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN uv sync 

CMD ["/app/run_monitor.sh"]
