FROM ghcr.io/astral-sh/uv:python3.12-bookworm

USER root

WORKDIR /app
COPY ./src /app
COPY pyproject.toml uv.lock /app/
COPY docker/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN uv sync --index-url https://mirrors.aliyun.com/pypi/simple

CMD ["/app/entrypoint.sh"]
